name: Unit and Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  greeting: 
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello everyone from the pipleline!'